Remove "--" if it exists in extra options
FuegoFro/GitChildBranchHelpers pull request #3
Opened 2017-07-19 03:42 UTC by ravron

`argparse` doesn't remove `--` if it's passed, as it must be for `REMAINDER` args that start with `-`. This diff causes it to be removed if present before forwarding to `arc diff` or `arc land`, both of which choke on it otherwise.

2017-07-19 18:26 UTC, ravron commented
See below for some discussion:
https://lists.gt.net/python/python/1225814

2017-07-19 18:56 UTC, FuegoFro requested changes
Thank you for the change! Just a small change requested :)

2017-07-19 18:56 UTC, FuegoFro commented on src/subcommands/arc_diff_against_parent.py
> +            if "--" in extra_arc_diff_options:
Can we make this (and the other) check a bit more strict by having it just look for `--` at the beginning of the options and if it's there only remove the first entry?

2017-07-19 20:52 UTC, ravron commented on src/subcommands/arc_diff_against_parent.py
> +            if "--" in extra_arc_diff_options:
`.remove()` only removes the first matching entry already, but I'll also change it to just check the zeroth item.

2017-07-19 21:02 UTC, ravron commented
It's not clear that I can mark your requested changes as done, but they are :P

2017-07-21 02:30 UTC, FuegoFro approved these changes

2017-07-21 02:30 UTC, merged